function [som]=auto_map_simulation_output(so,cfg) 
% function [som]=auto_map_simulation_output(so,cfg) 
% % DO NOT EDITED THIS FILE
% %
% % This function was automatically generated by 
% % build_system.pl       
% %
% % It takes one argume (so), the output from run_simulation_generic and returns the data
% % structure 'som' with named fields for times, states, and outputs.

m = cfg.options.mi;

% the raw simulation output 
som.raw      = so;
som.times.sim_time = so.t; 
 


% Mapping state output
som.states.Ato          = so.x(:,m.states.Ato); 
som.states.C1o          = so.x(:,m.states.C1o); 
som.states.C2o          = so.x(:,m.states.C2o); 
som.states.Atd          = so.x(:,m.states.Atd); 
som.states.C2d          = so.x(:,m.states.C2d); 
som.states.C3d          = so.x(:,m.states.C3d); 



% Mapping output output
som.outputs.C_osi         = so.y(:,m.outputs.C_osi); 
som.outputs.C_osi_met     = so.y(:,m.outputs.C_osi_met); 
som.outputs.C_daco_c      = so.y(:,m.outputs.C_daco_c); 
som.outputs.C_daco_p      = so.y(:,m.outputs.C_daco_p); 



% Mapping time scales
som.times.hour         = so.t*1; 
som.times.days         = so.t*1/24; 
som.times.weeks        = so.t*1/168; 
