function [SIMINT_t, SIMINT_x, y] = auto_sim(S, SIMINT_output_times, SIMINT_initialstate)
% % DO NOT EDITED THIS FILE
% %
% % This function was automatically generated by 
% % build_system.pl       
% %
% % It is called internally by run_simulation_generic.m

% Running simulation
SIMINT_runsim_string  = sprintf('[SIMINT_t, SIMINT_x] = %s(@auto_odes, SIMINT_output_times, SIMINT_initialstate,[],S);', S.default_simopts.Solver);

eval(SIMINT_runsim_string);

%
% Mapping outputs
%
for SIMINT_TIMEIDX=1:length(SIMINT_t)
SIMINT_TIME = SIMINT_t(SIMINT_TIMEIDX);
% Pulling out the states for the current time
x = interp1(SIMINT_t, SIMINT_x, SIMINT_TIME);
% pulling out the inputs at the current simulation time
u = interp1(S.blocks.all_inputs(:,1), S.blocks.all_inputs, SIMINT_TIME);
% The first column is the interpolated time,
% so we remove that one.
u = u(1,2:end);
% Defining parameters 
kao         = u(1); 
CL1o        = u(2); 
V1o         = u(3); 
CL2o        = u(4); 
V2o         = u(5); 
MWo         = u(6); 
kad         = u(7); 
CLd         = u(8); 
V2d         = u(9); 
Qd          = u(10); 
V3d         = u(11); 
MWd         = u(12); 



%  Mapping states to their common names 
Ato          = x(1);
C1o          = x(2);
C2o          = x(3);
Atd          = x(4);
C2d          = x(5);
C3d          = x(6);
 y(SIMINT_TIMEIDX,1) = C1o;
 y(SIMINT_TIMEIDX,2) = C2o;
 y(SIMINT_TIMEIDX,3) = C2d;
 y(SIMINT_TIMEIDX,4) = C3d;
end
