function [dx] = auto_odes(SIMINT_TIME,x,S)
% % DO NOT EDITED THIS FILE
% %
% % This function was automatically generated by 
% % build_system.pl       
% %
% % It is called internally by run_simulation_generic.m
% pulling out the inputs at the current simulation time
u = interp1(S.blocks.all_inputs(:,1), S.blocks.all_inputs, SIMINT_TIME);
% The first column is the interpolated time,
% so we remove that one.
u = u(1,2:end);
% Defining parameters 
kao         = u(1); 
CL1o        = u(2); 
V1o         = u(3); 
CL2o        = u(4); 
V2o         = u(5); 
MWo         = u(6); 
kad         = u(7); 
CLd         = u(8); 
V2d         = u(9); 
Qd          = u(10); 
V3d         = u(11); 
MWd         = u(12); 



%  Mapping states to their common names 
Ato          = x(1);
C1o          = x(2);
C2o          = x(3);
Atd          = x(4);
C2d          = x(5);
C3d          = x(6);
SIMINT_dAto   = (- kao*Ato);
SIMINT_dC1o   = (kao*Ato/V1o 		- CL1o*C1o/V1o);
SIMINT_dC2o   = (CL1o*C1o/V2o	 	- CL2o*C2o/V2o);
SIMINT_dAtd   = (- kad*Atd);
SIMINT_dC2d   = (kad*Atd/V2d 		- Qd*C2d/V2d);
SIMINT_dC3d   = (Qd*C2d/V3d 		- CLd*C3d/V3d);


%remapping the ODEs back to dx
dx(1,1) = SIMINT_dAto; 
dx(2,1) = SIMINT_dC1o; 
dx(3,1) = SIMINT_dC2o; 
dx(4,1) = SIMINT_dAtd; 
dx(5,1) = SIMINT_dC2d; 
dx(6,1) = SIMINT_dC3d; 
